AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyFunction:
    Properties:
      CodeUri: s3://lambda.alluremedia.com.au/60de086cfe32d393c2a910dd3ed54735
      Description: Lambda function for Alexa RSS reader skill
      FunctionName: alexa-rss-reader
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
